# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Fetch fingerprint
        run: |
          FINGERPRINT="$(openssl s_client -connect gateway.discord.gg:443 < /dev/null 2>/dev/null | openssl x509 -fingerprint -noout -in /dev/stdin | sed 's/^SHA1 Fingerprint=//g' | sed 's/:/ /g' | tr '[:upper:]' '[:lower:]')"
          echo "FINGERPRINT=$FINGERPRINT" >> $GITHUB_ENV

      - name: Replace fingerprint in config
        run: sed -i "s/\(\/\*FINGERPRINT>>\*\/\)\"[a-zA-Z0-9 ]\{59\}\"\(\/\*<<FINGERPRINT\*\/\)/\1\"_$FINGERPRINT_\"\2/" config.h

      - name: Check status
        run: echo "DIRTY=$(git status --porcelain)" >> $GITHUB_ENV

      - name: Branch and commit
        if: ${{ env.DIRTY != '' }}
        run: |
          git config user.email "tim.m.porritt@gmail.com"
          git config user.name "GitHub Actions"

          DATETIME="$(date +%Y%m%d_%H%M%S)"
          git checkout -b update/$DATETIME-update-fingerprint
          git add config.h
          git commit -m "$DATETIME: Update gateway.discord.gg fingerprint"
          git push -u origin HEAD

